### PR TITLE
Expose error name independently of error message

### PR DESCRIPTION
**Pull request by twittwer**
Hi,
in my opinion the ability to interpret the name (type) of an error in the frontend/client would be useful.
I don't understand why the exposure of the name should depend on the existence of an error message.
That's why I would appreciate if the name would be exposed, if it specific defined.

My current version is still invoking the existence of an error message:
```javascript
if (error.name && (error.name !== "Error" || this.developmentMode || error.message))
    processedError.name = name;
```
If you agree with the independence, I would propose:
```javascript
if ((error.name && error.name !== "Error") || this.developmentMode)
    processedError.name = name;
```

Best Regards

### CODE REVIEW

**Comment by twittwer** [comment]
@19majkel94 Thx, would you agree to expose if by default - without any condition?

**Comment by 19majkel94** [comment]
I don't get why we print error name in production only if `error.message` exist. So it might happen that something went wrong on on the server and we get error code 500 with no info in response body 😆

**Comment by twittwer** [comment]
Ok, I've removed the condition :slightly_smiling_face:

**Comment by NoNameProvided** [comment]
@19majkel94 can we squash merge for cleaner history? Or just simple merge?

**Comment by 19majkel94** [comment]
@NoNameProvided I think yes, it should not be the problem with this PR case.

**Pull request merged**
