### PR TITLE
Support mixing classes & classDirs on RoutingControllerOptions

### PR DESCRIPTION
**Pull request by iDaN5x**
**This change allows us to mix between imported classes & classDirs on:**
- `RoutingContollerOptions.controllers`
- `RoutingContollerOptions. middlewares `
- `RoutingContollerOptions. interceptors ` 

This change also adds `package-lock.json` introduced by npm 5.

### CODE REVIEW

**Comment by iDaN5x** [comment]
@pleerock node:latest build is failing on all builds.
This PR should not affect lib flow by any means.

**Comment by iDaN5x** [comment]
The proposal seems solid, however, it'll be a breaking change for existing codebases.
While the move to index files is easy enough (hack, it can be automated), #255 is not shipped yet.
I suggest merging my PR as bug-fix, as it is valuable to allow mixing.

**Comment by 19majkel94** [comment]
But it's not a bug, it works as designed. And as I said, merging this will make mixing dirs and classes official and I think we (as a developers team) can't support this kind of bad practices.

You can easily do now a workaround by yourself with `as any` type casting.

**Comment by 19majkel94** [comment]
> #255 is not shipped yet.

But you can do `Object.values(middlewares)` now, this proposal just make it a official way as a way to depreciate importing from dirs.

**Comment by iDaN5x** [comment]
👍 thanks

**Comment by pleerock** [comment]
dude stop using "depreciate importing from dirs" expression 😆

**Pull request closed without merging**
