### PR TITLE
Simple UTs

### PR DESCRIPTION
**Pull request by gjdass**
2 very simple UTs to start. More may follow.
Express server with routing-controllers.
Testing with mocha-typescript and chai-http if a call to a route returns the right output.

Related (partially) to #218. Some more examples need to be added.

Question tho : is it OK to put package.json and tsconfig.json into that new subfolder ? I hesitated, cause if not, it won't work out of the box cause of packages missing

### CODE REVIEW

**Comment by gjdass** [comment]
OK I will answer to myself since Travis is giving me some feedback.
I have moved the local conf of the folder to the global conf of the project.
Hope it's OK.

**Comment by 19majkel94** [comment]
I don't see any values of this. You just showed how to use chai-http which has a simple API.
The ask in #218 was about unit testing controllers, not integration/end-to-end endpoints testing.

Please create more advanced controllers with injected services, body params, query params, etc. and show how to test controllers.

**Comment by gjdass** [comment]
Hi. 

Indeed that's quite simple for now. I planned to push others UTs so I guess we gonna wait for further commits before a possible merge.

I'll work on that. 

_Sent from my OnePlus ONE E1003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gjdass** [comment]
I've pushed one more UT with Service injection.
I'm learning while coding these (I also do this on a proper project).

Something I don't understand tho : I had to `Container.set()` my service in order to make the thing work, which I don't have into my personal project.
Also I can't figure out how to change my container during tests. If I do it in the static `beforeAll` it's fine, but in tests themselves, nop. Something dumb I don't understand for sure.

**Comment by pleerock** [comment]
I think those changes must be part of separate repository, something like `routing-controllers-test-example` repository which contains test, just like https://github.com/pleerock/routing-controllers-express-demo . Or we even can add changes to that repository instead of creating a new one

**Comment by NoNameProvided** [comment]
@pleerock If I remember correctly you aimed to keep the demo repo simple. Btw I would move the whole sample folder to different repository and add a link here in the readme.

**Comment by pleerock** [comment]
> @pleerock If I remember correctly you aimed to keep the demo repo simple

yeah, thats right. But maybe we can add basic testing functionality as well. But totally not part of this repository.

**Comment by NoNameProvided** [comment]
Lets close this then

**Pull request closed without merging**
