### PR TITLE
Stream type support for express driver

### PR DESCRIPTION
**Pull request by Luke265**

### CODE REVIEW

**Comment by pleerock** [comment]
you made lot of dangerous changes. This part of code is complicated and without reason. I wont be able to accept this PR until all changes would be clear. If possible please make as small amount of changes as possible before we proceed. Thank you for this PR

**Comment by Luke265** [comment]
I've reduced code changes. Not sure why codecov returns errors.

**Comment by pleerock** [comment]
Looks much better now. You'll also need to create a test case to cover this issue.

**Comment by pleerock** [comment]
@Luke265 did you have chance to finish this PR?

**Comment by 19majkel94** [comment]
Closing in favour of #285.

**Pull request closed without merging**
