### PR TITLE
missing "typings" in package.json file

### PR DESCRIPTION
**Pull request by aliai**
this is required for typescript to find and resolve the module and its typings :)

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### CODE REVIEW

**Comment by pleerock** [comment]
thank you for this PR. But isnt it "index.d.ts" by default when you dont specify a "main" at all?

**Comment by aliai** [comment]
Well, the `main` is present, the `typings` was missing. I suppose it used to work without `typings`, but I am not entirely sure. They moved away from `typings` package management from TypeScript 2.0 if I am not mistaken, and introduced this gem as an alternative. We are using TypeScript 2.0.10 now and it complains that it cannot find the module, but after manually adding this line to the `package.json` it worked flawlessly :)

not sure why Travis is failing :(

Thanks for the great work btw!

**Comment by pleerock** [comment]
sorry my bad looks like I completely forgot about this PR, just saw it still hangs here. Apologies again!

**Comment by aliai** [comment]
thanks mate :)

**Pull request merged**
