### PR TITLE
Custom driver support

### PR DESCRIPTION
**Pull request by 19majkel94**
This PR makes two things:
- remove `Driver` interface and normal `BaseDriver` class in favor of one merged abstract class `BaseDriver`
- export `createServer` function to create routing-controller app with 3rd party driver + refactor of basic `createExpressServer` etc. to use unified generic function

### CODE REVIEW

**Comment by pleerock** [comment]
Looks okay please @NoNameProvided review it

**Comment by 19majkel94** [comment]
@NoNameProvided ping!
Please review and merge it 😉

**Comment by 19majkel94** [comment]
Fuck this, I need this changes right now in my new PR, so I'm merging my changes by myself as it's accepted 😆

**Comment by NoNameProvided** [comment]
Lol, I had it open for days as I had no time, now I reviewed and I saw it already merged. Looks good btw so merge is ok.

**Pull request merged**
