### PR TITLE
dynamic redirect

### PR DESCRIPTION
**Pull request by Diluka**
1. empty result behave like old one
2. string result override the default in @Redirect
3. object result using template-url to generate url

https://github.com/pleerock/routing-controllers/issues/159

### CODE REVIEW

**Comment by marshall007** [comment]
@Diluka I think it would also make sense to support `@Redirect()` with no arguments and allowing the controller method to return a string URL.

**Comment by Diluka** [comment]
@marshall007 
Diving into the driver, it decide whether there have redirections by checking the redirect string if not empty.

**Comment by pleerock** [comment]
You forgot to make url argument optional in `@Redirect` decorator. Also please add docs regarding to this new functionality.

**Comment by Diluka** [comment]
@pleerock 
url argument is designed to be not optional and adding docs

**Comment by pleerock** [comment]
Thank you! Released in `0.7.0-alpha.15`

**Pull request merged**
